### ISSUE TITLE
Register parcels through selecting a layer

### ISSUE THREAD

**Issue by patricknoack** [sommergis/agknow_qgis2#2]
Would be helpful if parcels could be registered through the plugin, e.g. by selecting an open  layer which has been opened or created in QGIS.

**Comment by sommergis** [comment]
This feature would be interesting, but we should define the requirements more precisely:
geometry would be easy to obtain from the selected feature(s), but what about the attributes (crop, entity, name, planting date, harvest date) ?

possible options:
- "batch registering":
should we accept only a certain data model with the aforementioned attribute list that is ready for registration?
alternatively we could define a mapping of attributes for selected layer (only possible if there is such data in the selected layer), e.g.<br>
![image](https://user-images.githubusercontent.com/22645408/50113110-4f6a3100-0241-11e9-9b74-1196f35ea5ed.png)
then select 1...n features in specified layer and click on register

- "registering one-by-one" (after each selection has changed)
if a feature has been selected in QGIS, we take the geometry from the selected feature and a popup will be displayed in which the user may enter the attributes (-> registering only one by one)
problem here: selection must only contain one object

**Comment by patricknoack** [comment]
Well, it is basically up to you :-;

I think it would be sufficient to source  the geometry for the selected polygon feature: you may consider splitting the process of  selecting or creating a polygon from assigning text attributes - it is a different process. 

Another option would be to source the information from database entries (link column names), as you suggested.

My  biggest concern was that I had to digitize the geometries on the portal despite the fact that I had them stoted in the QGIS project as shape files anyway.

**Comment by sommergis** [comment]
So we would go for option "registering one-by-one" first.

**Comment by sommergis** [comment]
Adressed in Version 0.7.2
